///////////////////////////////////////////////////////////
//  Entidad.cs
//  Implementation of the Class Entidad
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:58:12
//  Original author: pmmoy
///////////////////////////////////////////////////////////

namespace Dominio {

using System;
	public abstract class Entidad {

		public String Id { get; set; }

		protected Entidad(){
			Id = Guid.NewGuid().ToString();
		}

	}//end Entidad

}//end namespace Dominio