///////////////////////////////////////////////////////////
//  EstadosReserva.cs
//  Implementation of the Class EstadosReserva
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:58:12
//  Original author: pmmoy
///////////////////////////////////////////////////////////


namespace Dominio {
	public enum EstadosReserva : int {

		Iniciada,
		Activada,
		Finalizada,
    Anulada

  }//end EstadosReserva

}//end namespace Dominio