///////////////////////////////////////////////////////////
//  ExcepcionDominio.cs
//  Implementation of the Class ExcepcionDominio
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:58:12
//  Original author: pmmoy
///////////////////////////////////////////////////////////


namespace Dominio {

using System;
	public class ExcepcionDominio : Exception {
		/// 
		/// <param name="mensaje"></param>
		public ExcepcionDominio(String mensaje): base(mensaje){

		}

		/// 
		/// <param name="mensaje"></param>
		/// <param name="isReglaValida"></param>
		public static void LanzarCuando(bool isReglaValida, String mensaje){
			if(isReglaValida)
            throw new ExcepcionDominio(mensaje);
		}

	}//end ExcepcionDominio

}//end namespace Dominio