///////////////////////////////////////////////////////////
//  Itinerario.cs
//  Implementation of the Class Itinerario
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:11:59
//  Original author: pmmoy
///////////////////////////////////////////////////////////


namespace Dominio {
	public class Itinerario : Entidad {

		public Cliente ClienteInt { get; set; }
		public Vehiculo VehiculoInt { get; set; }
		public int Dias {  get; set; }
		public double Monto { get; set; }

		public Itinerario(){

		}


	}//end Itinerario

}//end namespace Dominio