///////////////////////////////////////////////////////////
//  MedioPago.cs
//  Implementation of the Class MedioPago
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:58:13
//  Original author: pmmoy
///////////////////////////////////////////////////////////



namespace Dominio {
  public class MedioPago : Entidad {

    private String descripcion;
    public String Descripcion { get => descripcion; set { ExcepcionDominio.LanzarCuando(string.IsNullOrEmpty(value), "Descripción inválida"); descripcion = value; } }
    public MedioPago(){
    }

	}//end MedioPago

}//end namespace Dominio