///////////////////////////////////////////////////////////
//  Vehiculo.cs
//  Implementation of the Class Vehiculo
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:58:13
//  Original author: pmmoy
///////////////////////////////////////////////////////////



using System;

namespace Dominio {
	public class Vehiculo : Entidad {

    private String modelo;
    private String marca;
    private int ano;
    private String serial;
    private double tarifaDia;

    public String Modelo { get => modelo; set { ExcepcionDominio.LanzarCuando(string.IsNullOrEmpty(value), "Modelo inválido"); modelo = value; } }
    public String Marca { get => marca; set { ExcepcionDominio.LanzarCuando(string.IsNullOrEmpty(value), "Marca inválida"); marca = value; } }
    public int Ano { get => ano; set { ExcepcionDominio.LanzarCuando(value < 1900 && DateTime.Now.Year > value, "Año inválido"); ano = value; } }
    public String Serial { get => serial; set { ExcepcionDominio.LanzarCuando(string.IsNullOrEmpty(value), "Serial inválido"); serial = value; } }
    public double TarifaDia { get => tarifaDia; set { ExcepcionDominio.LanzarCuando(value < 0.00, "Tarifa inválida"); tarifaDia = value; } }
    public bool IsDisponible { get; set; }


		public Vehiculo(){
      IsDisponible = true;
		}

	}//end Vehiculo

}//end namespace Dominio