///////////////////////////////////////////////////////////
//  MedioPagoRepositorioEF.cs
//  Implementation of the Class MedioPagoRepositorioEF
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:04:01
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;
using Aplicacion;
namespace Infraestructura {
	public class MedioPagoRepositorioEF : RepositorioBaseEF<MedioPago>, IMedioPagoRepositorio {

		public MedioPagoRepositorioEF(Context context) : base(context){

		}

	}//end MedioPagoRepositorioEF

}//end namespace Infraestructura