///////////////////////////////////////////////////////////
//  ReservaRepositorioEF.cs
//  Implementation of the Class ReservaRepositorioEF
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:04:01
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;
using Aplicacion;

namespace Infraestructura {
	public class ReservaRepositorioEF : RepositorioBaseEF<Reserva>, IReservaRepositorio {

		public ReservaRepositorioEF(Context context) : base(context){

		}

	}//end ReservaRepositorioEF

}//end namespace Infraestructura