///////////////////////////////////////////////////////////
//  VehiculoRepositorioEF.cs
//  Implementation of the Class VehiculoRepositorioEF
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:05:32
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;
using Aplicacion;
using Microsoft.EntityFrameworkCore;

namespace Infraestructura {
	public class VehiculoRepositorioEF : RepositorioBaseEF<Vehiculo>, IVehiculoRepositorio {

		public VehiculoRepositorioEF(Context context) : base(context){    

    }
    /// 
    /// <param name="itinerarios"></param>
    public void ProcesarItinerario(Itinerario[] itinerarios){

			foreach(var itinerario in itinerarios)
			{ 
        _context.Set<Itinerario>().Add(itinerario);
        _context.SaveChanges();
      }

		}

	}//end VehiculoRepositorioEF

}//end namespace Infraestructura