///////////////////////////////////////////////////////////
//  IClienteRepositorio.cs
//  Implementation of the Interface IClienteRepositorio
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:59:27
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;

namespace Aplicacion {
	public interface IClienteRepositorio : IRepositorioBase<Cliente> {

	}//end IClienteRepositorio

}//end namespace Aplicacion