///////////////////////////////////////////////////////////
//  IMedioPagoRepositorio.cs
//  Implementation of the Interface IMedioPagoRepositorio
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:02:59
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;

namespace Aplicacion {
	public interface IMedioPagoRepositorio : IRepositorioBase<MedioPago> {

	}//end IMedioPagoRepositorio

}//end namespace Aplicacion