///////////////////////////////////////////////////////////
//  IRepositorioBaseT.cs
//  Implementation of the Interface IRepositorioBase<T>
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:59:27
//  Original author: pmmoy
///////////////////////////////////////////////////////////


namespace Aplicacion {
	public interface IRepositorioBase<T> {

		/// 
		/// <param name="entidad"></param>
		void Crear(T entidad);

		/// 
		/// <param name="entidad"></param>
		/// <param name="id"></param>
		void Actualizar(T entidad, String id);

		/// 
		/// <param name="id"></param>
		void Borrar(String id);

		/// 
		/// <param name="id"></param>
		T Detallar(String id);

		T[] ListarTodos();
	}//end IRepositorioBase<T>

}//end namespace Aplicacion