///////////////////////////////////////////////////////////
//  IVehiculoRepositorio.cs
//  Implementation of the Interface IVehiculoRepositorio
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 14:59:27
//  Original author: pmmoy
///////////////////////////////////////////////////////////


using Dominio;

namespace Aplicacion {
	public interface IVehiculoRepositorio : IRepositorioBase<Vehiculo> {

		/// 
		/// <param name="itinerarios"></param>
		void ProcesarItinerario(Itinerario[] itinerarios);
	}//end IVehiculoRepositorio

}//end namespace Aplicacion