///////////////////////////////////////////////////////////
//  Repuesta.cs
//  Implementation of the Class Repuesta
//  Generated by Enterprise Architect
//  Created on:      12-feb.-2024 15:26:31
//  Original author: pmmoy
///////////////////////////////////////////////////////////


namespace Aplicacion {
	public class Repuesta<T> {
		public T Dato { get; set; }
		public bool IsValida { get; set; }
		public String Mensaje { get; set; }

	}//end Repuesta

}//end namespace Aplicacion